// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'book.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Book _$BookFromJson(Map<String, dynamic> json) => _Book(
  bookUrl: json['bookUrl'] as String,
  tocUrl: json['tocUrl'] as String,
  origin: json['origin'] as String? ?? 'loc_book',
  originName: json['originName'] as String,
  name: json['name'] as String,
  author: json['author'] as String,
  kind: json['kind'] as String?,
  customTag: json['customTag'] as String?,
  coverUrl: json['coverUrl'] as String?,
  customCoverUrl: json['customCoverUrl'] as String?,
  intro: json['intro'] as String?,
  customIntro: json['customIntro'] as String?,
  remark: json['remark'] as String?,
  charset: json['charset'] as String?,
  type: (json['type'] as num?)?.toInt() ?? 8,
  group: (json['group'] as num?)?.toInt() ?? 0,
  latestChapterTitle: json['latestChapterTitle'] as String?,
  latestChapterTime: (json['latestChapterTime'] as num?)?.toInt() ?? 0,
  lastCheckTime: (json['lastCheckTime'] as num?)?.toInt() ?? 0,
  lastCheckCount: (json['lastCheckCount'] as num?)?.toInt() ?? 0,
  totalChapterNum: (json['totalChapterNum'] as num?)?.toInt() ?? 0,
  durChapterTitle: json['durChapterTitle'] as String?,
  durChapterIndex: (json['durChapterIndex'] as num?)?.toInt() ?? 0,
  durChapterPos: (json['durChapterPos'] as num?)?.toInt() ?? 0,
  durChapterTime: (json['durChapterTime'] as num?)?.toInt() ?? 0,
  wordCount: json['wordCount'] as String?,
  canUpdate: json['canUpdate'] as bool? ?? true,
  order: (json['order'] as num?)?.toInt() ?? 0,
  originOrder: (json['originOrder'] as num?)?.toInt() ?? 0,
  variable: json['variable'] as String?,
  readConfig: json['readConfig'] as String?,
  syncTime: (json['syncTime'] as num?)?.toInt() ?? 0,
);

Map<String, dynamic> _$BookToJson(_Book instance) => <String, dynamic>{
  'bookUrl': instance.bookUrl,
  'tocUrl': instance.tocUrl,
  'origin': instance.origin,
  'originName': instance.originName,
  'name': instance.name,
  'author': instance.author,
  'kind': instance.kind,
  'customTag': instance.customTag,
  'coverUrl': instance.coverUrl,
  'customCoverUrl': instance.customCoverUrl,
  'intro': instance.intro,
  'customIntro': instance.customIntro,
  'remark': instance.remark,
  'charset': instance.charset,
  'type': instance.type,
  'group': instance.group,
  'latestChapterTitle': instance.latestChapterTitle,
  'latestChapterTime': instance.latestChapterTime,
  'lastCheckTime': instance.lastCheckTime,
  'lastCheckCount': instance.lastCheckCount,
  'totalChapterNum': instance.totalChapterNum,
  'durChapterTitle': instance.durChapterTitle,
  'durChapterIndex': instance.durChapterIndex,
  'durChapterPos': instance.durChapterPos,
  'durChapterTime': instance.durChapterTime,
  'wordCount': instance.wordCount,
  'canUpdate': instance.canUpdate,
  'order': instance.order,
  'originOrder': instance.originOrder,
  'variable': instance.variable,
  'readConfig': instance.readConfig,
  'syncTime': instance.syncTime,
};
